sudo: false

cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    - "$HOME/.cache"
    - "$HOME/nvm"

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
  - rm -rf $HOME/.sbt/ghpages

language: scala

stages:
  - name: build
    if: tag IS blank
  - name: release
    if: tag IS present

jobs:
  include:
    - stage: build
      if: commit_message !~ /^\[doc/
      env: PROJECT=code-format
      jdk: openjdk11
      script: ./scalafmt --test
    - stage: build
      if: tag IS blank AND branch = master AND type != pull_request
      env: PROJECT=docs
      jdk: openjdk11
      before_install:
        - export PATH=${PATH}:./vendor/bundle
        - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
          openssl aes-256-cbc -K $encrypted_dffb32b3dd1e_key -iv $encrypted_dffb32b3dd1e_iv
          -in travis/deploy-airframe-travis.enc -out travis/deploy-airframe-travis -d; chmod 600 travis/deploy-airframe-travis;
          cp travis/deploy-airframe-travis $HOME/.ssh/id_rsa; fi
      install:
        - rvm use 2.6.0 --install --fuzzy
        - gem update --system
        - gem install sass
        - gem install jekyll -v 3.8.5
      script:
        - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then
          cd $TRAVIS_BUILD_DIR && ./sbt docs/publishMicrosite; fi
    - stage: build
      if: tag IS blank AND branch = master AND type != pull_request AND commit_message !~ /^\[doc/
      env: PROJECT=publish
      jdk: openjdk8
      script:
        - cd $TRAVIS_BUILD_DIR && ./scripts/publish.sh
    - stage: build
      if: commit_message !~ /^\[doc/
      env: SCALA_VERSION=2.12.10 PROJECT=projectJVM
      jdk: openjdk8
      services: postgresql
      before_script: psql -c 'create database travis_ci_test;' -U postgres
      script:
        - ./sbt ++$SCALA_VERSION "; coverage; ${PROJECT}/test; ${PROJECT}/coverageReport"
        - "./sbt ${PROJECT}/coverageAggregate && bash <(curl -s https://codecov.io/bash)"
    - stage: build
      if: commit_message !~ /^\[doc/
      env: SCALA_VERSION=2.13.0 PROJECT=projectJVM2_13
      jdk: openjdk11
      services: postgresql
      before_script: psql -c 'create database travis_ci_test;' -U postgres
      script: ./sbt ++$SCALA_VERSION "${PROJECT}/test"
    - stage: build
      if: commit_message !~ /^\[doc/
      env: SCALA_VERSION=2.12.10 PROJECT=projectJS
      jdk: openjdk11  # Scala.js 0.6.27 didn't work with jdk11
      script: ./sbt ++$SCALA_VERSION ${PROJECT}/test
    - stage: build
      if: tag IS blank AND branch = master AND type != pull_request AND commit_message !~ /^\[doc/
      env: SCALA_VERSION=2.11.12 PROJECT=projectJVM
      # Build Scala 2.11 support only for master and releases
      jdk: openjdk8
      services: postgresql
      before_script: psql -c 'create database travis_ci_test;' -U postgres
      script: ./sbt ++$SCALA_VERSION ${PROJECT}/test
    - stage: release
      env: PROJECT=publish
      jdk: openjdk8
      script:
        - cd $TRAVIS_BUILD_DIR && ./scripts/publish.sh

env:
  global:
    - secure: ZQqfUfKOWF0xmuErGX9UuWjdjcIWzTqm99stB85Q7RlDpZaLIj4iubOq9uiu208FbdlxgahuNIC9mreF6XJ0Di7JbxxFNXS0k2ESmmA9IlaxUe6XVpPwSCMB+J22DplyOzximXx6iLzE77xfWPfRqr/RXsJh1wqpvfyGXigPFNqSaIzDDz6ElYkWlm84yzOIeozurvFhj7KGM01THlCsGSkxsQOHjJHy81CL/KwK8+W/1eV1Af05wVsG9y+Lf0i2/e7E1orRw/b1Tj3SNwdl4JAzDGo39qUD54d/xlgBXuj/zZLZa+7JJTwa3TNzvOLv0kDqf7G4JxeKFJRCsh/StfCrOGr4xTqLQIwCmP5P/3F9VTM9C+tvGx/+xdAu0n21R1FWCHrdSL4iCxkfxojEF1wzVnWZjdA/281fKsFatPK5uy1qFun0Oombjlp5UXzUJpfhHL/h2G0FB3x1Fg5iNSzAYSzWsbGKfOm1ef6G2JoTY9/MhDQ/ImiE5JMBisVR3eBD2v75D5jHreeTcCMKmhfo3R8M5JiVhA1VCqP1MHZ617g3x4QzxcSXo/7g0Y5ph0pUvfv9lEItkiageasfkCGLlDYoRLjheyUnjCIFindu6iXD0REr3vpPHcz6CEArB6QqnXvjTUo6oz7JJ00uQbRwsRuJ9odAdaO+IEcvzXc=
    - secure: gpfTAafeJwgoJc69OaPfOFBfjG+IZ9oWfvJ44ZKj1YtVUbo9s77n0u9gNlskYeVahbBe3VdLB0C6yWTlwOrDcHxj27TSVAc6qpS9WFCa0+1+op2H93LXx+cpWoQtLEasPXs9khZfhzRUq/2SY54YZMVK3YzNOUagjSETsR9rcOLdT9TOqlH2tuACB2iQdGDwumNGCP0e4FPFhoNlzaPHUfhXMEMXuDf/2qzItaWbjPWqEEiBBF2+PN2S4Xxf//EYuog1FAT4Gsdsg+KoApOtVbSWjr1M1tzayoFLnnRghuUsOMo+Y5hv2r9jkofmjIqVCNpSMkWPCjD0K4UY06v3VaXu9q7A9Rdn1TPip+t+y661kjoEBrc1HKcUWgRfgSTB5YNJl197chuNLvprwSTU2ri1eBXsjpWfivn0W3dNz7Pr7UaqX/7GBbiAi/Ko0PFcPktGHVuU+A8TBEZx8F090TdIcKhctDYw8sbbog0F1JOY4xP+QIOhovapLQlzjrZdA8dVdOfXLs7OG5L6goIujRdUlzcJ/T0LHc33+t3VbY8q8elKN1CGfpt6uYsrwvVoEmthqIXBhXP3CeqGJIgfvi9pRm0pXi+Rfehzr6uoV7IFX0BG7ofvU9y3gF2PJT3rvx5BHK8yts9obFf69kRqwXeQ+HIyQDZma2jdl6Td/z0=
    - secure: WNznVihW/4pNAiPTyE0P4MY8gK+0d5uzNPS32kGC/vOu9gvlIPY5EwPAFOTYKC5T2Hf7fw/6KoOK08ek2YJGTkJ/v26H8XuqJKJawmqQ6S+J9p9Qpl8LEHU4TCx9FLRqC+z+wr9lP2rzlMkguDBHPl/Lv29RzCp3l+vSfhyXTaS3TdnAO7u6Eo349l6PBbdbgifd5YCBJ7+TGlf+y1fHKPIPFSHgrtMPo3afM3IAp6uBeR0ucLBcr3G/26pgRmuwmIHJSOCYqCJ9bYE8dygaRrU9fBF+jmHWVJybvOIrVOze+z2oswhT6XZBO6IRWRFldL7/dE8sGKNfHSRSmhSnFsLf90HNtZVatqmco9rv3iEQQmo7/fpYhSdF16IlCuNrELx3Yrr+sFiGGpTYWIfqQSLre1+09C4+iSW0NF0znhq2/qgz0kmXaACjT7Y8p7I6YYUW37I2fesIGf+b50ieK3nNq4fz2eSs0aXXzDQ4sW96JLNWG1NDQpset8VgEleh48bHO9TqZx8zqyqLZNCjYEXOa2AtCbDOL7CDTZqmDlfLQkT2uX2wQO1aquFy7s720pI9VDU/wtZZIKadFL/nMCupEIwMnVX0VtcFnEFz6MHHXr4X3LT0rMIlO7IShUDnJu4Vvwa/J9ym3RJnqa2CJNpvU2b38FOoyewiZJAzfKw=
