name: Snapshot Release

on:
  push:
    branches:
      - master
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.github/workflows/snapshot.yml'
    tag:
      - '!v*'

jobs:
  publish_snapshots:
    name: Publish snapshots
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 10000
      # Fetch all tags so that sbt-dynver can find the previous release version
      - run: git fetch --tags
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Get Airframe version
        run: echo "AIRFRAME_VERSION=$(./scripts/dynver.sh)" >> $GITHUB_ENV
      - name: Check Airframe version
        run: echo ${AIRFRAME_VERSION}
      - name: Post version number to Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # wvlet dev-snapshot channel
          channel-id: 'C04CC79BZ7A'
          slack-message: "Publishing a snapshot version of airframe: `${{ env.AIRFRAME_VERSION }}`"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      - name: Publish snapshots
        env:
          SONATYPE_USERNAME: '${{ secrets.SONATYPE_USER }}'
          SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASS }}'
        run: |
          ./sbt publishSnapshots
      - name: Publish snapshots of AirSpec
        env:
          SONATYPE_USERNAME: '${{ secrets.SONATYPE_USER }}'
          SONATYPE_PASSWORD: '${{ secrets.SONATYPE_PASS }}'
        run: |
          ../sbt publishSnapshots
        working-directory: ./airspec
      - name: Notify the completion to Slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # wvlet dev-snapshot channel
          channel-id: 'C04CC79BZ7A'
          slack-message: "Published a snapshot version of airframe: `${{ env.AIRFRAME_VERSION }}`"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
