name: CI

on: [push, pull_request]

jobs:
  code_format:
    name: Code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: scalafmt test
        run: ./scalafmt --test
  test_2_12:
    name: Scala 2.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Scala 2.12 test with coverage test
        run: ./sbt "; coverage; projectJVM/test; projectJVM/coverageReport"
      - name: Generate a coverage report
        run: ./sbt projectJVM/coverageAggregate
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}} #required
          file: ./projectJVM/target/scala-2.12/scoverage-report/scoverage.xml

  test_2_13:
    name: Scala 2.13
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Scala 2.13 test
        run: ./sbt ++2.13.1 projectJVM2_13/test
  test_2_11:
    name: Scala 2.11
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Scala 2.11 test
        run: ./sbt ++2.11.12 projectJVM/test
  test_js:
    name: Scala.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Scala.js test
        run: ./sbt projectJS/test
