name: CI

on:
  pull_request:
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'
      - '.github/workflows/test.yml'
  push:
    branches:
      - master
    paths:
      - '**.scala'
      - '**.java'
      - '**.sbt'
      - '.scalafmt.conf'

jobs:
  code_format:
    name: Code format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: scalafmt
        run: ./sbt scalafmtCheckAll
      - name: scalafmt airspec
        run: ../sbt scalafmtCheckAll
        working-directory: ./airspec
      - name: scalafmt sbt-airframe
        run: ./sbt scalafmtCheckAll
        working-directory: ./sbt-airframe
  test_2_12:
    name: Scala 2.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: zulu@1.11
      - name: Scala 2.12 test
        run: ./sbt ++2.12.15 projectJVM/test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala 2.12
  test_2_13:
    name: Scala 2.13
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: zulu@1.11
      - name: Scala 2.13 test
        run: ./sbt projectJVM/test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala 2.13
  test_2_13_lastet_jdk:
    name: Scala 2.13 + JDK17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: zulu@1.17
      - name: Scala 2.13 + JDK17 test
        run: ./sbt projectJVM/test
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala 2.13 + JDK17
  test_3:
    name: Scala 3.x (Dotty)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: zulu@1.11
      - name: Scala 3.x test
        # Only use a limited number of tests until AirSpec and DI can support Scala 3
        run: DOTTY=true ./sbt "projectDotty/compile; dottyTest/run"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala 3.x
  test_js:
    name: Scala.js / Scala 2.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: zulu@1.11
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Node.js setup
        run: ./scripts/scalajs-setup.sh
      - name: Scala.js test
        run: JVM_OPTS=-Xmx4g ./sbt "; projectJS/test"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala.js / Scala 2.12
  test_js_2_13:
    name: Scala.js / Scala 2.13
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: zulu@1.11
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Node.js setup
        run: ./scripts/scalajs-setup.sh
      - name: Scala.js test
        run: JVM_OPTS=-Xmx4g ./sbt ++2.13.6 "; projectJS/test"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala.js / Scala 2.13
  test_airspec:
    name: AirSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v11
        with:
          java-version: zulu@1.11
      - name: Scala JVM and Scala.js Test
        run: ../sbt "++airspecJVM/test; ++airspecJS/test"
        working-directory: ./airspec
      - name: Scala 3 Test
        run: DOTTY=true ../sbt airspecJVM/test
        working-directory: ./airspec
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report AirSpec
