name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.filter.outputs.tests }}
    steps:
      - uses: actions/checkout@v5
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            tests:
              - '**.scala'
              - '**.java'
              - '**.sbt'
              - '.scalafmt.conf'
              - '.github/workflows/test.yml'
              - 'project/build.properties'
              - AIRSPEC_VERSION

  code_format:
    name: Code format
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - name: scalafmt in Scala 2.x
        run: ./sbt "++ 2.13; scalafmtCheckAll"
      - name: scalafmt in Scala 3
        run: ./sbt scalafmtCheckAll
      - name: scalafmt airspec
        run: ../sbt scalafmtCheckAll
        working-directory: ./airspec
      - name: scalafmt sbt-airframe
        run: ./sbt scalafmtCheckAll
        working-directory: ./sbt-airframe
  test_2_12:
    name: Scala 2.12
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Scala 2.12 test
        run: ./sbt "++2.12; projectJVM/test"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala 2.12
          annotate_only: true
          detailed_summary: true
  test_2_13:
    name: Scala 2.13
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Scala 2.13 test
        run: ./sbt "++2.13; projectJVM/test"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala 2.13
          annotate_only: true
          detailed_summary: true
  test_3:
    name: Scala 3
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Scala 3.x test
        # Test only Scala 3 supported projects
        run: ./sbt "++ 3; projectDotty/test; dottyTest/run"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala 3.x
          annotate_only: true
          detailed_summary: true
  test_3_latest:
    name: Scala 3.7.x
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Scala 3.7.x test
        # Test only Scala 3 supported projects
        run: SCALA_VERSION=3.7.1 ./sbt "projectDotty/test; dottyTest/run"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala 3.7.x
          annotate_only: true
          detailed_summary: true
  test_3_latest_jdk:
    name: Scala 3 / JDK17
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'
      - name: Scala 3 test
        # Test only Scala 3 supported projects
        run: ./sbt "++ 3; projectDotty/test; dottyTest/run"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala 3 / JDK17
          annotate_only: true
          detailed_summary: true
  test_integration:
    name: Scala 3 / Integration Test
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Node.js setup
        run: ./scripts/setup-scalajs.sh
      - name: Integration Test
        run: ./sbt "++ 3; projectIt/test"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Integration Test
          annotate_only: true
          detailed_summary: true
  test_js:
    name: Scala.js / Scala 2.12
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Node.js setup
        run: ./scripts/setup-scalajs.sh
      - name: Scala.js test
        run: JVM_OPTS=-Xmx4g ./sbt "++ 2.12; projectJS/test"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala.js / Scala 2.12
          annotate_only: true
          detailed_summary: true
  test_js_2_13:
    name: Scala.js / Scala 2.13
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Node.js setup
        run: ./scripts/setup-scalajs.sh
      - name: Scala.js test
        run: JVM_OPTS=-Xmx4g ./sbt "++ 2.13; projectJS/test"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala.js / Scala 2.13
          annotate_only: true
          detailed_summary: true
  test_js_3:
    name: Scala.js / Scala 3
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Node.js setup
        run: ./scripts/setup-scalajs.sh
      - name: Scala.js test
        run: JVM_OPTS=-Xmx4g ./sbt "++ 3; projectJS/test"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala.js / Scala 3
          annotate_only: true
          detailed_summary: true
  test_native_3:
    name: Scala Native / Scala 3
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Scala Native test
        run: JVM_OPTS=-Xmx4g ./sbt "++ 3; projectNative/test"
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report Scala Native / Scala 3
          annotate_only: true
          detailed_summary: true
  test_airspec:
    name: AirSpec
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.tests == 'true'
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Scala JVM and Scala.js Test
        run: ../sbt "++airspecJVM/test; ++airspecJS/test"
        working-directory: ./airspec
      - name: Scala Native Test
        run: ../sbt "++ 3; airspecNative/test"
        working-directory: ./airspec
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        if: always() # always run even if the previous step fails
        with:
          report_paths: '**/target/test-reports/TEST-*.xml'
          check_name: Test Report AirSpec
          annotate_only: true
          detailed_summary: true
